# Generated by Django 5.2.6 on 2025-09-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or short label, e.g. 🛠️', max_length=32)),
                ('price', models.CharField(blank=True, help_text='e.g. $50/hr or Fixed', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
