# Generated by Django 5.2.6 on 2025-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('management', 'Management'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
