# Generated by Django 5.2.6 on 2025-09-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_alter_service_category_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='accent',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_section',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('projects', 'Projects'), ('experience', 'Experience'), ('skills', 'Skills')], default='home', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='density',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
